### ISSUE TITLE
Include most recent generated pdf of the manual

### ISSUE THREAD

**Issue by ibaranov-cp** [warthog-cpr/warthog-user-manual#8]
I known it's not standard to include build artefacts, but this way we can point to a specifically versioned manual PDF online easily. Thoughts @majcote @tonybaltovski @cbogdon

**Comment by ibaranov-cp** [comment]
Also, please remove usage of Consolas, Arial (Windows only...) and either remove or include DINPro for use (again, if this is public) as these are not easily available.

Lastly, might be worth configuring and using rubber to remove need to re-run latex several times:
http://tex-talk.net/2011/12/building-documents-with-rubber/

**Comment by cbogdon** [comment]
Ok by me!

*Chris Bogdon* | *Marketing Specialist* | *Clearpath Robotics*
1.800.301.3863 x 707 | cbogdon@clearpathrobotics.com
97 Randall Dr, Waterloo, ON N2V 1C5, Canada

<https://mail.google.com/> <https://mail.google.com/>
*​Early-bird rates end Sept 30. R**egister here: * https://
<https://mail.google.com/mail/u/0/goog_1325438498>goo.gl/6gvupK

**Comment by ibaranov-cp** [comment]
Ok, fixing via a big notice on the README pointing to our online guide.
Fixing fonts and other updates in the next pull request.
